import { AgentInfo, FlowEdge, FlowNode, WorkItem, AgentChatMessage, ExecutionAuditLog } from '../types';

export const AGENTS: Record<string, AgentInfo> = {
  user: {
    id: 'user_1',
    name: 'Tech Lead (You)',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    color: '#E3E3E3',
    specialty: 'Product Direction & Architecture Review',
  },
  project_agent: {
    id: 'agent_project',
    name: 'Project Orchestrator Agent',
    role: 'project_agent',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    color: '#9AA0A6',
    specialty: 'Task Breakdown & Backlog Management',
  },
  architect_agent: {
    id: 'agent_arch',
    name: 'System Architect Agent',
    role: 'architect_agent',
    avatar: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=120&auto=format&fit=crop&q=80',
    color: '#BDC1C6',
    specialty: 'System Design & State Machine DAG',
  },
  backend_agent: {
    id: 'agent_backend',
    name: 'Backend Core Agent',
    role: 'backend_agent',
    avatar: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=120&auto=format&fit=crop&q=80',
    color: '#8AB4F8',
    specialty: 'Express / DB / Auth & Business Logic',
  },
  frontend_agent: {
    id: 'agent_frontend',
    name: 'Frontend UI Agent',
    role: 'frontend_agent',
    avatar: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=120&auto=format&fit=crop&q=80',
    color: '#FDD663',
    specialty: 'React 19 / Tailwind / State & Animations',
  },
  qa_agent: {
    id: 'agent_qa',
    name: 'QA & Verification Agent',
    role: 'qa_agent',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    color: '#F28B82',
    specialty: 'E2E Testing, Security Audits & Load Test',
  },
};

export const INITIAL_WORK_ITEMS: WorkItem[] = [
  {
    id: 'WI-101',
    title: '用户认证与权限控制中枢系统 (Core Auth & RBAC)',
    description: '主任务：构建包含 JWT 令牌签发、OAuth2 多协议集成、RBAC 角色权限矩阵及密码重置流程的企业级认证模块。',
    type: 'epic',
    status: 'in_progress',
    priority: 'P0',
    assignee: AGENTS.project_agent,
    reporter: AGENTS.user,
    createdAt: '2026-08-25 09:30',
    updatedAt: '2026-08-26 00:45',
    subItemIds: ['WI-102', 'WI-103', 'WI-104', 'WI-105'],
    isRootEpic: true,
    stateNodeId: 'node_epic_auth',
    estimatedHours: 40,
    loggedHours: 18,
    progress: 55,
    activePrdVersion: 'v1.1',
    prdVersions: [
      {
        version: 'v1.1',
        title: '用户认证与权限控制中枢系统 (Core Auth & RBAC) - PRD v1.1',
        createdAt: '2026-08-25 10:45',
        author: AGENTS.project_agent,
        giteaCommit: {
          repo: 'gitea.corp.ai/enterprise/core-auth',
          branch: 'main',
          commitHash: '8f9a12c',
          commitUrl: 'https://gitea.corp.ai/enterprise/core-auth/commit/8f9a12c',
          filePath: 'docs/PRD_CORE_AUTH.md',
        },
        summary: '响应 Tech Lead 架构评审意见：升级 JWT 算法为 RS256 非对称加密，补充 Redis 黑名单与 TOTP RFC 6238 双因子规范。',
        content: '# 用户认证与权限控制中枢系统 (Core Auth & RBAC) - PRD v1.1\n\n> 状态：当前生效规格 (Active Gitea Specification)\n> 仓库：gitea.corp.ai/enterprise/core-auth (branch: main)',
        comments: [
          {
            id: 'comm-init-1',
            sectionId: 'sec-3',
            sectionTitle: '3.0 核心 API 契约与鉴权协议',
            targetQuote: '采用 JWT 令牌签发与鉴权机制',
            content: '需要明确指定 JWT 算法为 RS256 并暴露 /.well-known/jwks.json 公钥端点，避免 HS256 对称秘钥泄露。',
            author: AGENTS.user,
            createdAt: '2026-08-25 10:20',
            resolved: true,
            resolutionNote: 'PM Agent 已在 v1.1 的 Section 3.1 中采纳 RS256 签名标准与 JWKS 公钥发现端点。',
          },
          {
            id: 'comm-init-2',
            sectionId: 'sec-4',
            sectionTitle: '4.0 2FA 双因子安全与 TOTP 流程',
            targetQuote: '支持双因子认证',
            content: '请补充防暴力破解滑动窗口限制（如 10 分钟输错 5 次冻结 15 分钟）。',
            author: AGENTS.user,
            createdAt: '2026-08-25 10:22',
            resolved: true,
            resolutionNote: 'PM Agent 已在 Section 4.2 补充 Brute-Force Guard 与 Redis 滑动窗口限流规范。',
          },
        ],
        isActive: true,
      },
      {
        version: 'v1.0',
        title: '用户认证与权限控制中枢系统 (Core Auth & RBAC) - PRD v1.0',
        createdAt: '2026-08-25 09:30',
        author: AGENTS.project_agent,
        giteaCommit: {
          repo: 'gitea.corp.ai/enterprise/core-auth',
          branch: 'main',
          commitHash: '3d8e91a',
          commitUrl: 'https://gitea.corp.ai/enterprise/core-auth/commit/3d8e91a',
          filePath: 'docs/PRD_CORE_AUTH.md',
        },
        summary: '初始版本：基于用户自然语言需求编排生成的认证中枢规格说明书。',
        content: '# 用户认证与权限控制中枢系统 (Core Auth & RBAC) - PRD v1.0\n\n初始构建版本。',
        comments: [],
        isActive: false,
      },
    ],
    tags: ['Auth', 'Security', 'P0-Release', 'Backend'],
    transitionHistory: [
      {
        id: 'th-1',
        timestamp: '2026-08-25 09:30:12',
        fromStatus: 'backlog',
        toStatus: 'todo',
        actor: AGENTS.project_agent,
        reason: 'Agent 对话需求确认完成，由 Project Agent 建立主任务工单。',
        durationInPrevState: '0m',
      },
      {
        id: 'th-2',
        timestamp: '2026-08-25 10:15:00',
        fromStatus: 'todo',
        toStatus: 'in_progress',
        actor: AGENTS.project_agent,
        reason: '主任务移入 [In Progress]，系统自动触发工单分解引擎，下发 4 个子任务。',
        notes: 'Spawning sub-tasks WI-102, WI-103, WI-104, WI-105.',
        durationInPrevState: '44m 48s',
      },
    ],
    commits: [
      {
        id: 'c-101-1',
        hash: '7f9a12c8b0e11894d4560938f29910d6e8a09bc1',
        shortHash: '7f9a12c',
        message: 'chore(arch): init auth state machine and database schema definition',
        author: AGENTS.architect_agent,
        timestamp: '2026-08-25 11:20:00',
        filesChanged: 4,
        insertions: 218,
        deletions: 12,
        files: [
          {
            name: 'src/db/schema/users.ts',
            status: 'added',
            diffSnippet: '+ export interface UserSchema {\n+   id: string;\n+   email: string;\n+   passwordHash: string;\n+   role: "admin" | "engineer" | "guest";\n+ }',
          },
          {
            name: 'src/config/jwt.config.ts',
            status: 'added',
            diffSnippet: '+ export const JWT_SECRET = process.env.JWT_SECRET || "dev-secret-key";\n+ export const TOKEN_EXPIRY = "24h";',
          },
        ],
      },
    ],
    auditLogs: [
      {
        id: 'log-101-1',
        timestamp: '2026-08-25 09:30:15',
        level: 'INFO',
        stepName: '需求意图语义解析与领域范围定界 (Scope Boundary Definition)',
        phase: 'planning',
        executor: AGENTS.project_agent,
        summary: '完成对用户输入 "用户认证中心与 RBAC" 的实体抽取与边界判定，生成标准 Epic 规范。',
        durationMs: 142,
        details: {
          inputParams: {
            rawPrompt: '构建包含 JWT 令牌签发、OAuth2 多协议集成、RBAC 角色权限矩阵及密码重置流程的企业级认证模块。',
            targetPlatform: 'Express + Vite Fullstack',
            securityLevel: 'Enterprise-Tier-3',
          },
          stdout: '[INFO] Initializing NL Intent Parser v3.2\n[INFO] Identified entities: [JWT, OAuth2, RBAC, PasswordReset]\n[INFO] Generated Epic ID: WI-101 with 4 planned subtasks.\n[SUCCESS] Boundary validated against OWASP ASVS Level 2.',
          outputResult: {
            epicId: 'WI-101',
            status: 'planning_completed',
            estimatedStoryPoints: 21,
            slaTargetDays: 5,
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-101-2',
        timestamp: '2026-08-25 10:15:02',
        level: 'SUCCESS',
        stepName: '工单裂变引擎调度 (Task Decomposition Dispatch)',
        phase: 'planning',
        executor: AGENTS.project_agent,
        summary: '主工单跃迁至 In Progress，成功生成 4 个专职子任务并自动绑定状态机 DAG 节点。',
        durationMs: 286,
        details: {
          inputParams: {
            parentEpicId: 'WI-101',
            triggerEvent: 'status_transition_in_progress',
          },
          stdout: '[INFO] Task Decomposition Engine triggered.\n[INFO] Spawned subtask: WI-102 (Backend Core Agent)\n[INFO] Spawned subtask: WI-103 (Frontend UI Agent)\n[INFO] Spawned subtask: WI-104 (QA Security Agent)\n[INFO] Spawned subtask: WI-105 (System Architect Agent)\n[INFO] Injected DAG edges: node_epic_auth -> [node_jwt_backend, node_login_ui, node_rbac_matrix]',
          outputResult: {
            spawnedWorkItems: ['WI-102', 'WI-103', 'WI-104', 'WI-105'],
            dagNodesSynced: 4,
            routingStrategy: 'Parallel-Async',
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-101-3',
        timestamp: '2026-08-25 11:20:10',
        level: 'INFO',
        stepName: '架构基线设计与数据库 Schema 审查 (Schema Review)',
        phase: 'review',
        executor: AGENTS.architect_agent,
        summary: '系统架构师完成 Auth 状态机与 users 表结构签名验证，并合入架构代码提交。',
        durationMs: 410,
        details: {
          inputParams: {
            schemaFiles: ['src/db/schema/users.ts', 'src/config/jwt.config.ts'],
            encryptionStandard: 'Argon2id + RS256',
          },
          stdout: '[INFO] Validating schema constraints...\n[INFO] Primary keys: UUIDv4 confirmed\n[INFO] Indexing: email(unique), role(indexed), last_login_at(indexed)\n[SUCCESS] Commit 7f9a12c verified and signed.',
          outputResult: {
            commitHash: '7f9a12c',
            tablesCreated: ['users', 'roles', 'permissions', 'token_blacklists'],
          },
          exitCode: 0,
        },
      },
    ],
    itemChatMessages: [
      {
        id: 'ic-101-1',
        sender: AGENTS.project_agent,
        content: '你好！我是负责 **[WI-101] 用户认证中枢** 的 Project Orchestrator Agent。目前 4 个子任务已全部派发完毕，正在并发推进中。您可以在这里直接对我下达工单维度的全局指令。',
        timestamp: '10:16',
      },
    ],
  },
  {
    id: 'WI-102',
    title: 'JWT 令牌颁发与双因子校验中间件',
    description: '实现基于 RS256 算法的 JWT 签名、Token 刷新逻辑、多因子 (2FA/TOTP) 校验机制及 Redis 黑名单失效拦截。',
    type: 'task',
    status: 'in_progress',
    priority: 'P0',
    assignee: AGENTS.backend_agent,
    reporter: AGENTS.project_agent,
    createdAt: '2026-08-25 10:15',
    updatedAt: '2026-08-26 01:05',
    parentId: 'WI-101',
    parentTitle: '用户认证与权限控制中枢系统 (Core Auth & RBAC)',
    subItemIds: [],
    stateNodeId: 'node_jwt_backend',
    estimatedHours: 12,
    loggedHours: 8,
    progress: 75,
    tags: ['Backend', 'Security', 'Express', 'JWT'],
    transitionHistory: [
      {
        id: 'th-102-1',
        timestamp: '2026-08-25 10:15:05',
        fromStatus: 'backlog',
        toStatus: 'todo',
        actor: AGENTS.project_agent,
        reason: '主任务 WI-101 触发分解生成该子任务。',
      },
      {
        id: 'th-102-2',
        timestamp: '2026-08-25 11:30:20',
        fromStatus: 'todo',
        toStatus: 'in_progress',
        actor: AGENTS.backend_agent,
        reason: 'Backend Core Agent 领取任务并开始编写 JWT 中间件与 Redis 令牌缓存。',
        durationInPrevState: '1h 15m',
      },
    ],
    commits: [
      {
        id: 'c-102-1',
        hash: '9d2e4b31a8cf56170942e0123512a9bc451df67e',
        shortHash: '9d2e4b3',
        message: 'feat(auth): implement verifyJwtToken middleware & token revocation list',
        author: AGENTS.backend_agent,
        timestamp: '2026-08-25 16:40:11',
        filesChanged: 3,
        insertions: 145,
        deletions: 14,
        files: [
          {
            name: 'src/middleware/auth.ts',
            status: 'modified',
            diffSnippet: '+ export const authMiddleware = (req, res, next) => {\n+   const authHeader = req.headers.authorization;\n+   if (!authHeader?.startsWith("Bearer ")) return res.status(401).json({ error: "Missing token" });\n+   const token = authHeader.split(" ")[1];\n+   req.user = verifyToken(token);\n+   next();\n+ };',
          },
          {
            name: 'src/services/tokenRevocation.ts',
            status: 'added',
            diffSnippet: '+ export async function isTokenRevoked(jti: string): Promise<boolean> {\n+   return redisClient.exists(`blacklist:${jti}`);\n+ }',
          },
        ],
      },
    ],
    auditLogs: [
      {
        id: 'log-102-1',
        timestamp: '2026-08-25 11:30:25',
        level: 'INFO',
        stepName: '代码生成环境沙箱预热与密钥对生成 (Keypair Provisioning)',
        phase: 'codegen',
        executor: AGENTS.backend_agent,
        summary: '生成 4096-bit RSA 非对称密钥对 (Private / Public PEM)，配置安全环境变量。',
        durationMs: 340,
        details: {
          inputParams: {
            algorithm: 'RS256',
            modulusLength: 4096,
            publicKeyEncoding: 'spki/pem',
            privateKeyEncoding: 'pkcs8/pem',
          },
          stdout: '[INFO] Generating RSA Keypair for RS256 token signing...\n[INFO] Public key sha256 checksum: a18f43ec90...3df\n[SUCCESS] Keys loaded into in-memory secure vault.',
          outputResult: {
            keyAlgorithm: 'RS256',
            keyExpiryDays: 90,
            status: 'ready',
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-102-2',
        timestamp: '2026-08-25 14:10:00',
        level: 'DEBUG',
        stepName: 'Express 中间件 AST 解析与拦截流水线注入 (Middleware Pipeline Hook)',
        phase: 'compilation',
        executor: AGENTS.backend_agent,
        summary: '通过 TypeScript Compiler API 将 authMiddleware 注入到 /api/v1/* 路由前置管道。',
        durationMs: 185,
        details: {
          inputParams: {
            targetRouter: 'src/routes/api.ts',
            injectedMiddlewares: ['authMiddleware', 'rateLimitMiddleware', 'rbacGuard'],
          },
          stdout: '[DEBUG] Scanning Express routes for protection attributes...\n[DEBUG] Attached authMiddleware to 14 secure endpoints.\n[DEBUG] Bypass routes: [/api/v1/auth/login, /api/v1/auth/register, /api/health]',
          outputResult: {
            protectedEndpointsCount: 14,
            unprotectedEndpointsCount: 3,
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-102-3',
        timestamp: '2026-08-25 16:38:45',
        level: 'SUCCESS',
        stepName: '单测验证套件执行与 Redis 令牌注销测试 (Integration Assertion)',
        phase: 'testing',
        executor: AGENTS.backend_agent,
        summary: '执行 18 组单元测试用例，覆盖过期令牌、篡改签名、注销黑名单校验等边界情况。全部通过 (18/18)。',
        durationMs: 820,
        details: {
          inputParams: {
            testSuite: 'test/auth/jwt.test.ts',
            coverageThreshold: 90,
          },
          stdout: 'PASS test/auth/jwt.test.ts\n  ✓ should issue valid JWT token with user claims (32 ms)\n  ✓ should reject expired tokens gracefully (12 ms)\n  ✓ should block revoked jti tokens via Redis blacklist (18 ms)\n  ✓ should enforce TOTP 6-digit code validity window (45 ms)\n\nTest Suites: 1 passed, 1 total\nTests:       18 passed, 18 total\nSnapshots:   0 total\nTime:        0.82 s',
          assertions: [
            { name: 'Issue valid RS256 token', status: 'passed', durationMs: 32 },
            { name: 'Reject tampered signature', status: 'passed', durationMs: 14 },
            { name: 'Redis blacklisting revocation', status: 'passed', durationMs: 18 },
            { name: 'TOTP drift tolerance +-30s', status: 'passed', durationMs: 45 },
          ],
          outputResult: {
            passed: 18,
            failed: 0,
            codeCoverage: '94.6%',
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-102-4',
        timestamp: '2026-08-25 16:40:15',
        level: 'INFO',
        stepName: 'Git Commit 签名与代码提交 (Code Check-in)',
        phase: 'codegen',
        executor: AGENTS.backend_agent,
        summary: '生成 commit 9d2e4b3 并推送到远程跟踪分支，准备进入下一阶段安全渗透。',
        durationMs: 210,
        details: {
          inputParams: {
            branch: 'feature/auth-jwt-middleware',
            commitMessage: 'feat(auth): implement verifyJwtToken middleware & token revocation list',
          },
          stdout: '[master 9d2e4b3] feat(auth): implement verifyJwtToken middleware & token revocation list\n 3 files changed, 145 insertions(+), 14 deletions(-)\n create mode 100644 src/services/tokenRevocation.ts',
          outputResult: {
            commitSha: '9d2e4b31a8cf56170942e0123512a9bc451df67e',
          },
          exitCode: 0,
        },
      },
    ],
    itemChatMessages: [
      {
        id: 'ic-102-1',
        sender: AGENTS.backend_agent,
        content: '我是 **Backend Core Agent**，已完成 JWT 颁发、RS256 签名以及 Redis 令牌黑名单机制的代码编写与单测覆盖。当前任务进度 75%，如有任何参数微调（如 Token 有效期、TOTP 漂移容忍度等），请直接在下方发送指令。',
        timestamp: '16:42',
      },
    ],
  },
  {
    id: 'WI-103',
    title: '响应式登录与多因子认证 UI 界面',
    description: '包含密码登录、OAuth2 第三方快捷登录入口、动态验证码组件及 2FA 二维码扫描录入。',
    type: 'story',
    status: 'in_review',
    priority: 'P1',
    assignee: AGENTS.frontend_agent,
    reporter: AGENTS.project_agent,
    createdAt: '2026-08-25 10:15',
    updatedAt: '2026-08-25 22:15',
    parentId: 'WI-101',
    parentTitle: '用户认证与权限控制中枢系统 (Core Auth & RBAC)',
    subItemIds: [],
    stateNodeId: 'node_login_ui',
    estimatedHours: 10,
    loggedHours: 9,
    progress: 90,
    tags: ['Frontend', 'React', 'Tailwind', 'UI/UX'],
    transitionHistory: [
      {
        id: 'th-103-1',
        timestamp: '2026-08-25 10:15:05',
        fromStatus: 'backlog',
        toStatus: 'todo',
        actor: AGENTS.project_agent,
        reason: '主任务 WI-101 触发分解生成该子任务。',
      },
      {
        id: 'th-103-2',
        timestamp: '2026-08-25 13:00:00',
        fromStatus: 'todo',
        toStatus: 'in_progress',
        actor: AGENTS.frontend_agent,
        reason: 'Frontend Agent 开始设计与编写登录模态窗组件。',
      },
      {
        id: 'th-103-3',
        timestamp: '2026-08-25 22:15:30',
        fromStatus: 'in_progress',
        toStatus: 'in_review',
        actor: AGENTS.frontend_agent,
        reason: 'UI 研发完成，发起 PR #42 并请求 QA Agent 开展无障碍与响应式验收。',
        durationInPrevState: '9h 15m',
      },
    ],
    commits: [
      {
        id: 'c-103-1',
        hash: '4a1b8c9d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b',
        shortHash: '4a1b8c9',
        message: 'feat(ui): add modern glassy login dialog with 2FA TOTP input slots',
        author: AGENTS.frontend_agent,
        timestamp: '2026-08-25 21:50:00',
        filesChanged: 5,
        insertions: 320,
        deletions: 8,
        files: [
          {
            name: 'src/components/auth/LoginModal.tsx',
            status: 'added',
            diffSnippet: '+ export const LoginModal = () => {\n+   const [step, setStep] = useState<"credentials" | "totp">("credentials");\n+   return (\n+     <div className="auth-card p-6 bg-slate-900 rounded-xl">\n+       <h2>Sign in to DevWorkstation</h2>\n+     </div>\n+   );\n+ };',
          },
        ],
      },
    ],
    auditLogs: [
      {
        id: 'log-103-1',
        timestamp: '2026-08-25 13:10:00',
        level: 'INFO',
        stepName: 'Figma 设计令牌提取与 Tailwind 样式构建 (Design Token Sync)',
        phase: 'codegen',
        executor: AGENTS.frontend_agent,
        summary: '提取设计稿暗色模式色板与无障碍 WCAG 2.1 AA 对比度参数，构建响应式表单。',
        durationMs: 260,
        details: {
          inputParams: {
            theme: 'Google AI Studio Dark Neutral',
            wcagContrastMin: 4.5,
          },
          stdout: '[INFO] Parsing Design Tokens...\n[INFO] Generated 6 CSS custom properties.\n[INFO] WCAG AA Compliance Check: PASS (Ratio: 7.2:1)',
          outputResult: {
            status: 'tokens_ready',
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-103-2',
        timestamp: '2026-08-25 21:48:10',
        level: 'SUCCESS',
        stepName: 'Lighthouse 性能与无障碍门禁自动化检测 (Lighthouse CI Audit)',
        phase: 'testing',
        executor: AGENTS.frontend_agent,
        summary: 'Lighthouse 得分：Performance: 98, Accessibility: 100, Best Practices: 100, SEO: 96。',
        durationMs: 1450,
        details: {
          inputParams: {
            targetUrl: 'http://localhost:3000/#login',
            viewport: 'mobile & desktop',
          },
          stdout: 'Running Lighthouse CI on target route /#login...\n- Performance: 98/100\n- Accessibility: 100/100\n- Best Practices: 100/100\n- First Contentful Paint: 0.4s\n- Total Blocking Time: 0ms\n[SUCCESS] Quality Gate passed.',
          outputResult: {
            score: 98,
            accessibilityScore: 100,
          },
          exitCode: 0,
        },
      },
    ],
    itemChatMessages: [
      {
        id: 'ic-103-1',
        sender: AGENTS.frontend_agent,
        content: '我是 **Frontend UI Agent**！登录对话框与 2FA TOTP 6 位输入槽已完成并提交 PR #42，Lighthouse 跑分已达 98 分。请审查！',
        timestamp: '22:16',
      },
    ],
  },
  {
    id: 'WI-104',
    title: '自动化安全审计与渗透防护测试套件',
    description: '针对 Auth 模块进行密码爆破防护 (Rate Limiting)、SQL 注入防御、CSRF/XSS 渗透扫描和 JWT 弱密钥离线爆破测试。',
    type: 'task',
    status: 'blocked',
    priority: 'P0',
    assignee: AGENTS.qa_agent,
    reporter: AGENTS.project_agent,
    createdAt: '2026-08-25 10:15',
    updatedAt: '2026-08-26 00:30',
    parentId: 'WI-101',
    parentTitle: '用户认证与权限控制中枢系统 (Core Auth & RBAC)',
    subItemIds: [],
    stateNodeId: 'node_security_audit',
    estimatedHours: 8,
    loggedHours: 2,
    progress: 25,
    bottleneckReason: '等待后端部署预发布隔离沙箱 (WI-102 PR 合并) 与 Redis 容器证书就绪。',
    tags: ['Security', 'QA', 'Audit', 'Bottleneck'],
    transitionHistory: [
      {
        id: 'th-104-1',
        timestamp: '2026-08-25 10:15:05',
        fromStatus: 'backlog',
        toStatus: 'todo',
        actor: AGENTS.project_agent,
        reason: '主任务 WI-101 触发分解生成该子任务。',
      },
      {
        id: 'th-104-2',
        timestamp: '2026-08-25 17:00:00',
        fromStatus: 'todo',
        toStatus: 'in_progress',
        actor: AGENTS.qa_agent,
        reason: 'QA Agent 启动安全渗透用例准备。',
      },
      {
        id: 'th-104-3',
        timestamp: '2026-08-26 00:30:10',
        fromStatus: 'in_progress',
        toStatus: 'blocked',
        actor: AGENTS.qa_agent,
        reason: '发现缺少 Staging 独立 Mock Redis 服务，触发阻塞标记并通报状态机。',
        notes: 'Bottleneck flagged: Dependency on WI-102 Staging cluster availability.',
      },
    ],
    commits: [],
    auditLogs: [
      {
        id: 'log-104-1',
        timestamp: '2026-08-25 17:05:00',
        level: 'INFO',
        stepName: 'OWASP ZAP 渗透扫描器配置初始化 (Security Test Setup)',
        phase: 'security_scan',
        executor: AGENTS.qa_agent,
        summary: '加载 OWASP Top 10 渗透用例字典与针对 JWT 的 6 种常见攻击向量。',
        durationMs: 290,
        details: {
          inputParams: {
            attackVectors: ['NoneAlgorithmAttack', 'KeyConfusion', 'JWKSInjection', 'SQLi', 'BruteForceRateLimit'],
          },
          stdout: '[INFO] Loaded 124 security vulnerability vectors.\n[INFO] Configuring active scanner on port 8080...',
          outputResult: {
            readyRules: 124,
          },
          exitCode: 0,
        },
      },
      {
        id: 'log-104-2',
        timestamp: '2026-08-26 00:30:05',
        level: 'WARN',
        stepName: '沙箱连接失败与瓶颈标记触发 (Sandbox Connection Timeout)',
        phase: 'security_scan',
        executor: AGENTS.qa_agent,
        summary: '无法连接到 staging-redis:6379 进行黑名单爆破验证，触发任务阻塞告警。',
        durationMs: 5200,
        details: {
          inputParams: {
            targetHost: 'staging-redis.internal',
            port: 6379,
            timeoutMs: 5000,
          },
          stdout: '[ERROR] connect ECONNREFUSED staging-redis.internal:6379\n[WARN] Redis cluster required to test token blacklist revocation.\n[WARN] Bottleneck raised: Halting automated security penetration run.',
          stackTrace: 'Error: Connection timeout after 5000ms\n  at RedisClient.connect (src/db/redis.ts:42:15)\n  at SecurityScanner.verifyBlacklist (test/sec/audit.ts:88:9)',
          outputResult: {
            bottleneckStatus: 'blocked',
            requiredAction: 'Provide active Redis container or mock service.',
          },
          exitCode: 1,
        },
      },
    ],
    itemChatMessages: [
      {
        id: 'ic-104-1',
        sender: AGENTS.qa_agent,
        content: '我是 **QA & Security Agent**。在执行 JWT 黑名单压力测试时，因 Staging 容器环境中的 Redis 未就绪而产生阻塞。您可以在流转图或本对话中下发解除指令，我将切换至内存 Mock 模式继续执行。',
        timestamp: '00:32',
      },
    ],
  },
  {
    id: 'WI-105',
    title: 'RBAC 角色权限矩阵与装饰器中间件',
    description: '支持自定义角色（Owner, Admin, Member, Viewer）及细粒度资源级动作（read:repo, write:flow, trigger:agent）。',
    type: 'task',
    status: 'todo',
    priority: 'P1',
    assignee: AGENTS.architect_agent,
    reporter: AGENTS.project_agent,
    createdAt: '2026-08-25 10:15',
    updatedAt: '2026-08-25 10:15',
    parentId: 'WI-101',
    parentTitle: '用户认证与权限控制中枢系统 (Core Auth & RBAC)',
    subItemIds: [],
    stateNodeId: 'node_rbac_matrix',
    estimatedHours: 8,
    loggedHours: 0,
    progress: 0,
    tags: ['Architecture', 'RBAC', 'Backend'],
    transitionHistory: [
      {
        id: 'th-105-1',
        timestamp: '2026-08-25 10:15:05',
        fromStatus: 'backlog',
        toStatus: 'todo',
        actor: AGENTS.project_agent,
        reason: '主任务 WI-101 触发分解生成该子任务。',
      },
    ],
    commits: [],
    auditLogs: [
      {
        id: 'log-105-1',
        timestamp: '2026-08-25 10:15:10',
        level: 'INFO',
        stepName: 'RBAC 权限矩阵模型定义排队就绪 (Queue Initialized)',
        phase: 'planning',
        executor: AGENTS.architect_agent,
        summary: 'RBAC 权限矩阵原型已锁定，排队等待 WI-102 JWT 中间件完成后合并。',
        durationMs: 80,
        details: {
          inputParams: {
            rolesCount: 4,
            permissionsCount: 28,
          },
          stdout: '[INFO] RBAC specification defined. Awaiting worker availability.',
          exitCode: 0,
        },
      },
    ],
    itemChatMessages: [
      {
        id: 'ic-105-1',
        sender: AGENTS.architect_agent,
        content: '我是 **System Architect Agent**，负责该任务的 RBAC 角色模型定义。当前工单在 Todo 队列，可随时下达指令提前激活。',
        timestamp: '10:16',
      },
    ],
  },
  {
    id: 'WI-106',
    title: '基于 WebSocket 的实时 Agent 协作状态广播协议',
    description: '主任务：建立多人/多 Agent 协同状态总线，支持光标同步、工单变更通知与状态机节点实时触发。',
    type: 'epic',
    status: 'done',
    priority: 'P1',
    assignee: AGENTS.backend_agent,
    reporter: AGENTS.user,
    createdAt: '2026-08-24 14:00',
    updatedAt: '2026-08-25 09:00',
    subItemIds: [],
    isRootEpic: true,
    stateNodeId: 'node_ws_bus',
    estimatedHours: 16,
    loggedHours: 15,
    progress: 100,
    tags: ['WebSocket', 'Realtime', 'Done'],
    transitionHistory: [
      {
        id: 'th-106-1',
        timestamp: '2026-08-24 14:00:00',
        fromStatus: 'backlog',
        toStatus: 'in_progress',
        actor: AGENTS.backend_agent,
        reason: '需求下达，立即开展全双工链路研发。',
      },
      {
        id: 'th-106-2',
        timestamp: '2026-08-25 09:00:00',
        fromStatus: 'in_progress',
        toStatus: 'done',
        actor: AGENTS.qa_agent,
        reason: '压力测试通过 (10,000 并发稳定)，正式验收上线。',
      },
    ],
    commits: [
      {
        id: 'c-106-1',
        hash: '1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d',
        shortHash: '1c2d3e4',
        message: 'feat(realtime): implement heartbeat ping/pong and event-broker multiplexer',
        author: AGENTS.backend_agent,
        timestamp: '2026-08-24 23:40:00',
        filesChanged: 4,
        insertions: 280,
        deletions: 10,
        files: [
          {
            name: 'src/server/socketHub.ts',
            status: 'added',
            diffSnippet: '+ export class SocketHub {\n+   broadcast(event: string, payload: unknown) {\n+     this.clients.forEach(c => c.send(JSON.stringify({ event, payload })));\n+   }\n+ }',
          },
        ],
      },
    ],
    auditLogs: [
      {
        id: 'log-106-1',
        timestamp: '2026-08-24 14:05:00',
        level: 'INFO',
        stepName: 'WebSocket 协议编解码与心跳广播设计 (Protocol Design)',
        phase: 'codegen',
        executor: AGENTS.backend_agent,
        summary: '实现 JSON 二进制消息通道与 30s 自动心跳重连检测。',
        durationMs: 310,
        details: {
          inputParams: {
            heartbeatIntervalMs: 30000,
            maxPayloadBytes: 65536,
          },
          stdout: '[INFO] SocketHub initialized.\n[INFO] Ping-Pong keepalive configured.',
          exitCode: 0,
        },
      },
      {
        id: 'log-106-2',
        timestamp: '2026-08-25 08:50:00',
        level: 'SUCCESS',
        stepName: '万级并发压力测试与最终验收 (Load Testing Benchmark)',
        phase: 'testing',
        executor: AGENTS.qa_agent,
        summary: '完成 10,000 活跃客户端并发广播压测，平均消息延迟 14ms，SLA 达成 99.99%。',
        durationMs: 3600,
        details: {
          inputParams: {
            concurrentClients: 10000,
            durationSeconds: 60,
          },
          stdout: 'Running k6 load test...\n- Virtual Users: 10,000\n- HTTP/WS Handshakes: 10,000 OK\n- Message Latency p95: 14.2ms\n- Packet Loss: 0.00%\n[SUCCESS] Milestone Approved.',
          outputResult: {
            p95LatencyMs: 14.2,
            packetLoss: 0,
          },
          exitCode: 0,
        },
      },
    ],
    itemChatMessages: [
      {
        id: 'ic-106-1',
        sender: AGENTS.backend_agent,
        content: '该任务已完成所有压测与验收！生产环境状态广播正常运行中。',
        timestamp: '09:02',
      },
    ],
  },
];

export const INITIAL_FLOW_NODES: FlowNode[] = [
  {
    id: 'node_start',
    title: '任务下达与需求澄清 (Spec Input)',
    type: 'start',
    status: 'completed',
    assignedAgent: AGENTS.project_agent,
    inputs: [],
    outputs: ['node_epic_auth'],
    bottleneck: false,
    duration: '12m',
    latencyMs: 140,
    x: 60,
    y: 180,
    description: '用户在 Agent 对话框下达高阶意图，经澄清生成初始规格说明书。',
  },
  {
    id: 'node_epic_auth',
    title: '主工单生成与分解 (WI-101 Core Auth)',
    type: 'process',
    status: 'completed',
    assignedAgent: AGENTS.project_agent,
    relatedWorkItemId: 'WI-101',
    inputs: ['node_start'],
    outputs: ['node_jwt_backend', 'node_login_ui', 'node_rbac_matrix'],
    bottleneck: false,
    duration: '45m',
    latencyMs: 320,
    x: 320,
    y: 180,
    description: '主 Work Item 进入 In Progress，触发自动分发：生成后端 JWT、前端 UI 与 RBAC 架构任务。',
  },
  {
    id: 'node_jwt_backend',
    title: 'JWT 签名与中间件 (WI-102 Backend)',
    type: 'agent_action',
    status: 'running',
    assignedAgent: AGENTS.backend_agent,
    relatedWorkItemId: 'WI-102',
    inputs: ['node_epic_auth'],
    outputs: ['node_security_audit', 'node_integration'],
    bottleneck: false,
    duration: '8h 15m (Active)',
    latencyMs: 450,
    x: 640,
    y: 80,
    description: '后端 Agent 正在实现 RS256 签名与 Redis 令牌防重放黑名单校验。',
  },
  {
    id: 'node_login_ui',
    title: '登录/2FA 组件构建 (WI-103 Frontend)',
    type: 'agent_action',
    status: 'running',
    assignedAgent: AGENTS.frontend_agent,
    relatedWorkItemId: 'WI-103',
    inputs: ['node_epic_auth'],
    outputs: ['node_integration'],
    bottleneck: false,
    duration: '9h (In Review)',
    latencyMs: 280,
    x: 640,
    y: 220,
    description: '前端 Agent 已完成 UI 并提交 PR，进入设计与可用性审查。',
  },
  {
    id: 'node_rbac_matrix',
    title: 'RBAC 权限策略构建 (WI-105 Architect)',
    type: 'process',
    status: 'idle',
    assignedAgent: AGENTS.architect_agent,
    relatedWorkItemId: 'WI-105',
    inputs: ['node_epic_auth'],
    outputs: ['node_integration'],
    bottleneck: false,
    duration: 'Queueing',
    x: 640,
    y: 360,
    description: '定义 Role-Permission 策略矩阵及动态权限拦截器。',
  },
  {
    id: 'node_security_audit',
    title: '自动化渗透审计 (WI-104 QA/Security)',
    type: 'condition',
    status: 'blocked',
    assignedAgent: AGENTS.qa_agent,
    relatedWorkItemId: 'WI-104',
    inputs: ['node_jwt_backend'],
    outputs: ['node_integration'],
    bottleneck: true,
    bottleneckMsg: '🚨 瓶颈告警：等待沙箱 Redis 集群就绪，已阻塞 45 分钟。',
    duration: '45m (Blocked)',
    latencyMs: 9800,
    x: 960,
    y: 80,
    description: '执行 OWASP Top 10 安全渗透套件，当前因隔离环境依赖被阻塞。',
  },
  {
    id: 'node_integration',
    title: '全栈联调与 E2E 验证 (Integration)',
    type: 'review',
    status: 'idle',
    assignedAgent: AGENTS.qa_agent,
    inputs: ['node_security_audit', 'node_login_ui', 'node_rbac_matrix'],
    outputs: ['node_deploy_staging'],
    bottleneck: false,
    duration: 'Estimated 2h',
    x: 1240,
    y: 200,
    description: '前后端端到端联调测试，验证完整用户登录、拦截与注销全生命周期。',
  },
  {
    id: 'node_deploy_staging',
    title: 'Staging 预发布部署 (Continuous Delivery)',
    type: 'deploy',
    status: 'idle',
    assignedAgent: AGENTS.project_agent,
    inputs: ['node_integration'],
    outputs: ['node_finish'],
    bottleneck: false,
    duration: 'Estimated 15m',
    x: 1520,
    y: 200,
    description: '自动化构建镜像，部署至预发布沙箱环境供最终人工验收。',
  },
  {
    id: 'node_finish',
    title: '工单关闭与版本归档 (Release Milestone)',
    type: 'end',
    status: 'idle',
    assignedAgent: AGENTS.project_agent,
    inputs: ['node_deploy_staging'],
    outputs: [],
    bottleneck: false,
    duration: '-',
    x: 1780,
    y: 200,
    description: '完成 Epic 目标，生成变更日志并同步至发布说明。',
  },
];

export const INITIAL_FLOW_EDGES: FlowEdge[] = [
  { id: 'e1', source: 'node_start', target: 'node_epic_auth', active: true },
  { id: 'e2', source: 'node_epic_auth', target: 'node_jwt_backend', active: true },
  { id: 'e3', source: 'node_epic_auth', target: 'node_login_ui', active: true },
  { id: 'e4', source: 'node_epic_auth', target: 'node_rbac_matrix', active: false },
  { id: 'e5', source: 'node_jwt_backend', target: 'node_security_audit', active: true, isBottleneck: true },
  { id: 'e6', source: 'node_jwt_backend', target: 'node_integration', active: false },
  { id: 'e7', source: 'node_login_ui', target: 'node_integration', active: false },
  { id: 'e8', source: 'node_rbac_matrix', target: 'node_integration', active: false },
  { id: 'e9', source: 'node_security_audit', target: 'node_integration', active: false, isBottleneck: true },
  { id: 'e10', source: 'node_integration', target: 'node_deploy_staging', active: false },
  { id: 'e11', source: 'node_deploy_staging', target: 'node_finish', active: false },
];

export const INITIAL_CHAT_MESSAGES: AgentChatMessage[] = [
  {
    id: 'msg-1',
    sender: AGENTS.user,
    content: '我们需要为当前系统构建一套高可用的用户认证中心（包含 JWT 签名、2FA 双因子认证和 RBAC 权限体系）。请先规划任务并生成工单。',
    timestamp: '09:28',
  },
  {
    id: 'msg-2',
    sender: AGENTS.project_agent,
    content: '收到需求！已分析核心技术链路，我已为您在看板创建主工单：**[WI-101] 用户认证与权限控制中枢系统**。\n\n**计划策略**：\n1. 主工单目前在 `Todo` 列；\n2. 一旦主工单移入 `In Progress`，系统将自动分解并指派子任务给 Backend Core Agent、Frontend Agent 及 QA Agent；\n3. 同步驱动状态机 DAG 图，实时观测任务依赖与执行瓶颈。',
    timestamp: '09:30',
    thoughtChain: [
      '解析用户自然语言需求 -> 提取关键词: JWT, 2FA, RBAC, Auth',
      '评估系统影响范围: Express Middleware, React UI, Security Test',
      '生成主工单 WI-101 (Epic)',
      '构建状态机 DAG 初始骨架: Spec -> Epic -> [Backend, Frontend, RBAC] -> Security Audit -> Integration',
    ],
    actionType: 'propose_task',
    actionPayload: {
      createdWorkItemId: 'WI-101',
    },
  },
  {
    id: 'msg-3',
    sender: AGENTS.user,
    content: '确认方案，请将 WI-101 移入 In Progress 并开始执行分解。',
    timestamp: '10:14',
  },
  {
    id: 'msg-4',
    sender: AGENTS.project_agent,
    content: '🚀 **已将 WI-101 移入 [In Progress]**！工单分解引擎已成功触发，已生成 4 个关联子工单并派发给对应 Agent：\n- 🔹 **WI-102** [Backend Agent]: JWT 令牌与双因子校验中间件 (已启动)\n- 🔹 **WI-103** [Frontend Agent]: 登录与 2FA UI 界面 (已提交 Review)\n- 🔹 **WI-104** [QA Agent]: 自动化安全审计与渗透测试 (⚠️ 检测到沙箱依赖瓶颈)\n- 🔹 **WI-105** [Architect Agent]: RBAC 角色权限矩阵 (排队中)',
    timestamp: '10:15',
    thoughtChain: [
      '检测到 WI-101 状态变更为 in_progress',
      '触发自动任务裂变规则 (Task Decomposition Hook)',
      '分配工单到专职 Agent 池并关联 parentId: WI-101',
      '更新状态机 DAG 节点状态，高亮活跃链路',
    ],
    actionType: 'spawn_subtasks',
    actionPayload: {
      createdWorkItemId: 'WI-101',
      spawnedSubItemIds: ['WI-102', 'WI-103', 'WI-104', 'WI-105'],
    },
  },
  {
    id: 'msg-5',
    sender: AGENTS.qa_agent,
    content: '⚠️ **状态机瓶颈预警**：WI-104 安全审计任务目前被标记为 `Blocked`。原因：缺少独立的 Staging Redis 沙箱实例，已在状态流转图中高亮该瓶颈节点。',
    timestamp: '00:31',
    thoughtChain: [
      '执行 Docker-compose staging 环境前置检查',
      '发现端口 6379 冲突且缺少隔离证书',
      '标记 WorkItem WI-104 状态为 blocked',
      '向状态机总线广播 isBottleneck: true 警报',
    ],
    actionType: 'state_change',
    actionPayload: {
      affectedNodeId: 'node_security_audit',
    },
  },
];
